-- =========================================================
-- COMMENTS: JOBS - MODULE 4
-- =========================================================
-- Metadata documentation for scheduled
-- operational automation jobs responsible for:
-- - Appointment status maintenance
-- - Sending appointment reminders
--
-- IMPORTANT:
-- pg_cron jobs are not native relational
-- schema objects.
--
-- Because of this, PostgreSQL does not allow:
-- - COMMENT ON JOB
-- - COMMENT ON CRON ENTRY
--
-- Therefore, job metadata must be documented
-- manually through structured SQL comments
-- inside the corresponding migration files.
-- =========================================================

-- The following is a conceptual documentation for a cron job.
-- cron.schedule('0 1 * * *', 'CALL prc_auto_update_no_show_appointments();')
-- Description: This job runs daily at 1:00 AM to automatically mark missed appointments as ''No-Show''.