-- =========================================================
-- PLACEHOLDER — NOT LOADED AT BOOTSTRAP
-- FILE: Comments/Schema/00_Core/00_Common_Functions_Comments.sql
-- =========================================================
-- PURPOSE: Reserved layout slot; no COMMENT ON targets.
-- Bootstrap/Loaders/05_Comments.sql skips this file.
-- =========================================================
